#!/usr/bin/env node
// Convert snarkjs verification_key.json to Rust constants for groth16-solana
// Usage: node parse_vk.js path/to/verification_key.json

const fs = require("fs");

const vkPath = process.argv[2] || "build/verification_key.json";
const vk = JSON.parse(fs.readFileSync(vkPath, "utf8"));

// Convert decimal string to 32-byte big-endian hex
function toBytes32BE(decStr) {
  let hex = BigInt(decStr).toString(16);
  hex = hex.padStart(64, "0");
  const bytes = [];
  for (let i = 0; i < 64; i += 2) {
    bytes.push(parseInt(hex.substring(i, i + 2), 16));
  }
  return bytes;
}

// Format byte array as Rust array literal
function formatRustBytes(bytes) {
  const lines = [];
  for (let i = 0; i < bytes.length; i += 16) {
    const chunk = bytes.slice(i, i + 16);
    lines.push("    " + chunk.map((b) => `${b}`).join(", ") + ",");
  }
  return lines.join("\n");
}

// G1 point: [x, y, z] -> [u8; 64] = x_be || y_be
function g1ToBytes(point) {
  return [...toBytes32BE(point[0]), ...toBytes32BE(point[1])];
}

// G2 point: [[x0, x1], [y0, y1], [z0, z1]] -> [u8; 128]
// EIP-197 format: x_imag(x1) || x_real(x0) || y_imag(y1) || y_real(y0)
function g2ToBytes(point) {
  return [
    ...toBytes32BE(point[0][1]), // x1 (imaginary)
    ...toBytes32BE(point[0][0]), // x0 (real)
    ...toBytes32BE(point[1][1]), // y1 (imaginary)
    ...toBytes32BE(point[1][0]), // y0 (real)
  ];
}

const alpha_g1 = g1ToBytes(vk.vk_alpha_1);
const beta_g2 = g2ToBytes(vk.vk_beta_2);
const gamma_g2 = g2ToBytes(vk.vk_gamma_2);
const delta_g2 = g2ToBytes(vk.vk_delta_2);
const ic = vk.IC.map((p) => g1ToBytes(p));

let output = `// Auto-generated by parse_vk.js from verification_key.json
// DO NOT EDIT MANUALLY

pub const VK_ALPHA_G1: [u8; 64] = [
${formatRustBytes(alpha_g1)}
];

pub const VK_BETA_G2: [u8; 128] = [
${formatRustBytes(beta_g2)}
];

pub const VK_GAMMA_G2: [u8; 128] = [
${formatRustBytes(gamma_g2)}
];

pub const VK_DELTA_G2: [u8; 128] = [
${formatRustBytes(delta_g2)}
];

pub const VK_IC: [[u8; 64]; ${ic.length}] = [
`;

for (let i = 0; i < ic.length; i++) {
  output += `    [\n`;
  output += formatRustBytes(ic[i]);
  output += `\n    ],\n`;
}
output += `];\n`;

console.log(output);
